name: release-gh-pages

on:
  push:
    tags:
      - "v*.*.*"

env:
  PUBLIC_URL: /bevy-jam-2/

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version-tag.outputs.VERSION }}
    steps:
      - name: Get tagged version
        id: version-tag
        run: echo "::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}"

  release-wasm:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Rust Targets
        run: rustup target add wasm32-unknown-unknown
      - name: install wasm-bindgen-cli
        run: |
          cargo install wasm-bindgen-cli
      - name: Build
        run: |
          cd launchers/wasm && cargo build --release --target wasm32-unknown-unknown
      - name: Wasm Bindgen
        run: |
          cd launchers/wasm
          wasm-bindgen --no-typescript --out-name bevy_game --out-dir dist --target web ../../target/wasm32-unknown-unknown/release/wasm-launcher.wasm
          cp -r ./static ./dist/
          cp -r ../../assets ./dist/
          cp index.html ./dist/
          cd ../../
      - name: Deploy, Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./launchers/wasm/dist
      - name: Itch.io
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_KEY}}
          gameData: ./launchers/wasm/dist/
          itchUsername: ${{secrets.ITCH_USERNAME}}
          itchGameId: ${{ secrets.ITCH_GAME_ID }}
          buildChannel: "html5"
